application:
  name: demo1
  metadata: "hello world"
  profile: "Dev"
  server:
    web:
      type: "fasthttp"
      address: ":8081"
      maxBody: 2096157
      static:
        patten: "/"
        webroot: "./Static"
